version: '3.7'
services:

  db:
    container_name: dev_db
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: dev.env
  web:
    build: .
    command: ["uwsgi", "--ini", "/code/uwsgi/uwsgi.ini" ]
    restart: always
    volumes:
      - .:/code
    env_file: dev.env
    depends_on:
      - db

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/etc/static
      - ./media:/etc/media
      - .:/code
      - /code/static:/etc/static
      - /code/media:/etc/media
    ports:
      - "80:80"
      - "443:443"



