version: '3.7'
services:

  db:
    container_name: dev_db
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: dev.env

  web:
    container_name: dev_backend
    build: .
    command: ["uwsgi","--ini","./uwsgi/uwsgi.ini" ]
    restart: always
    volumes:
      - .:/code
    env_file: dev.env
    depends_on:
      - db


  nginx:
    container_name: dev_web
    image: nginx:1.23.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www-html:/var/www/html
      - ./nginx/conf/default.conf.template:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
        - etc-letsencrypt:/etc/letsencrypt
        - www-html:/val/www/html
    command: certonly --webroot --webroot-patch=/val/www/html --email davidki329@gmail.com --agree-tos --no-eff-email -d furmandavid.info

