version: '3.7'
services:

  db:
    container_name: dev_db
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: dev.env

  web:
    container_name: dev_backend
    build: .
    command: ["uwsgi","--ini","./uwsgi/uwsgi.ini" ]
    restart: always
    volumes:
      - .:/code
    env_file: dev.env
    depends_on:
      - db


  nginx:
    container_name: dev_web
    image: nginx:1.23.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
      - .:/code
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
      image: certbot/certbot
      restart: unless-stopped
      volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


